### ISSUE TITLE
Falhas em fluxos de trabalho de edição

### ISSUE THREAD

**Issue by alexandre-mbm** [mapascoletivos/mapascoletivos#106]
Experimentei alguns bugs chatos [durante a Mapatona Copa do Mundo 2014](http://wiki.openstreetmap.org/wiki/Talk:Mapatona_Copa_do_Mundo_2014#Dificuldades_com_o_Mapas_Coletivos):

**1) O sistema não está gravando dados em alguns fluxos de trabalho**

Somente com alguns "macetes" foi possível utilizá-lo:
- Salvar um Conteúdo sempre duas vezes, especialmente no caso de uma reedição
- Em um Conteúdo, esperar a imagem de carregar completamente, antes de salvá-lo
- Não fiar-se no botão "Salvar alterações" que há para todo o conteúdo da camada
- Sempre verificar em outra aba do navegador, recarregando a página, a regravação do conteúdo

**2) Dupla importação dos mesmos pontos**

Eu importo um GPX e o sistema não responde. Então eu importo novamente, e o sistema não responde. Mas eu tenho a ideia de recarregar a página... e quando faço, está lá: todos os pontos do GPX foram gravados em duplicidade.

Sugestão para além da correção do bug: uma maneira de apagar vários pontos de uma vez.

**Comment by vgeorge** [comment]
Fechando esta issue por inatividade.
